name: EEGModalNet

channels:
  - conda-forge
  - pytorch
  - nvidia
  - default

dependencies:
  # - transformers
  - python
  - pip
  - pytest
  - pytorch
  - keras
  - torchvision
  - seaborn
  - pandas
  - flake8
  - ipykernel
  # - jupyter
  # - notebook
  - xarray
  - h5netcdf
  # - tensorboard
  - dvc>3
  # - dvc-gdrive
  # - dvc-ssh
  # - openai
  - scikit-learn
  # - mne
  # - wordcloud
