name: eegnet

channels:
  - conda-forge
  - default

dependencies:
  - python
  - pip
  - pytorch::pytorch
  - pytorch-lightning
  - pytorch::torchaudio
  - torchinfo
  - seaborn
  - pandas
  - openpyxl
  - flake8
  - ipykernel
  - jupyter
  - notebook
  - xarray
  - h5netcdf
  - tensorboard
  - dvc>3
  - dvc-gdrive
  - scikit-learn
  # - ray-tune
