name: EEGModalNet

channels:
  - pytorch
  - nvidia
  - conda-forge
  - default

dependencies:
  - transformers
  - python
  - pip
  - pytest
  - pytorch
  - torchvision
  - seaborn
  - pandas
  - flake8
  - ipykernel
  - jupyter
  - notebook
  - xarray
  - h5netcdf
  - tensorboard
  - dvc>3
  - dvc-gdrive
  - dvc-ssh
  - scikit-learn
  - mne

  - pip:
    - keras>3
